blog/urls.py
from django.urls import path

from blog.views import PostListView, PostDetailView,add_comment

urlpatterns = [
    path("", PostListView.as_view(), name="post_list"),
    path("categories/<slug:category>/", PostListView.as_view(), name="post_category"),
    path("authors/<slug:username>/", PostListView.as_view(), name="post_author"),
    path("posts/<slug:slug>/", PostDetailView.as_view(), name="post_detail"),
    path('post-add-comment/', add_comment, name="post_add_comment"),
]

djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include("main.urls")),
    path('shop/', include("products.urls")),
    path('users/', include("users.urls")),
    path('cart/', include("cart.urls")),
    path('favorites/', include("favorites.urls")),
    path('blog/', include("blog.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import os

from django.db import models
from django.utils.text import slugify

from users.models import User


def get_file_ext(file):
    return os.path.splitext(file)[1]


def post_name_generator(instance, file):
    ext = get_file_ext(file)
    return f"posts/{instance.slug}/{instance.slug}{ext}"


class Category(models.Model):
    title = models.CharField(max_length=64, verbose_name="عنوان")
    english_title = models.CharField(max_length=64, verbose_name="عنوان انگلیسی")
    slug = models.SlugField(db_index=True, editable=False)
    parent = models.ForeignKey("Category", on_delete=models.CASCADE, verbose_name="دسته بندی والد", null=True,
                               blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.english_title)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"


class Post(models.Model):
    title = models.CharField(max_length=128, verbose_name="عنوان")
    english_title = models.CharField(max_length=128, verbose_name="عنوان انگلیسی")
    slug = models.SlugField(max_length=128, editable=False)
    picture = models.ImageField(upload_to=post_name_generator, verbose_name="عکس")
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    category = models.ManyToManyField(Category, verbose_name="دسته بندی")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="نویسنده", editable=False)
    text = models.TextField(verbose_name="متن پست")
    is_active = models.BooleanField(default=True, verbose_name="فعال/غیرفعال")

    def save(self, *args, **kwargs):
        self.slug = slugify(self.english_title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "پست"
        verbose_name_plural = "پست ها"
        ordering = ("-created",)


class PostComment(models.Model):
    parent = models.ForeignKey("PostComment", on_delete=models.CASCADE, blank=True, null=True, verbose_name="والد")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="کاربر")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name="پست")
    created = models.DateTimeField(auto_now_add=True)
    text = models.TextField(verbose_name="متن نظر")

    class Meta:
        ordering = "-created",

blog/views.py
from django.http import JsonResponse
from django.template.loader import render_to_string

from blog.models import Post, Category, PostComment
from django.views.generic import ListView, DetailView


class PostListView(ListView):
    template_name = "blog/post-list.html"
    model = Post
    context_object_name = "posts"

    def get_queryset(self):
        queryset = super(PostListView, self).get_queryset()
        if category := self.kwargs.get("category"):
            queryset = queryset.filter(category__category__slug__exact=category)
        if author := self.kwargs.get("username"):
            queryset = queryset.filter(author__username__exact=author)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(PostListView, self).get_context_data(*args, **kwargs)
        categories = Category.objects.all()
        _context = {
            "categories": categories,
        }
        context.update(_context)
        return context


class PostDetailView(DetailView):
    template_name = "blog/post-detail.html"
    model = Post
    context_object_name = "post"

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        comments = PostComment.objects.filter(post_id=self.object.id)
        next_obj = Post.objects.filter(id=self.object.id + 1)
        next_obj_slug = None
        if next_obj.exists():
            next_obj_slug = next_obj.first().slug
        previous_obj = Post.objects.filter(id=self.object.id - 1)
        previous_obj_slug = None
        if previous_obj.exists():
            previous_obj_slug = previous_obj.first().slug
        categories = Category.objects.all()
        _context = {
            "categories": categories,
            "comments": comments,
            "next_obj_slug": next_obj_slug,
            "previous_obj_slug": previous_obj_slug,
        }
        context.update(_context)
        return context


def add_comment(request):
    if request.user.is_authenticated:
        parent_id = request.GET.get("parent_id")
        user_id = request.user.id
        post_id = request.GET.get("post_id")
        text = request.GET.get("text")
        post = Post.objects.filter(id=post_id)
        if post.exists():
            if text:
                if parent_id == "none":
                    new_comment = PostComment.objects.create(parent_id=None, user_id=user_id, post_id=post_id,
                                                             text=text)
                    new_comment.save()
                    comments = PostComment.objects.filter(post_id=post_id)
                    html_text = render_to_string("blog/includes/comment-component.html", {"comments": comments})
                    return JsonResponse({"html": html_text, "status": 200, "message": "نظر با موفقیت ثبت شد."})
                else:
                    parent_comment = PostComment.objects.filter(id=parent_id)
                    if parent_comment.exists():
                        new_comment = PostComment.objects.create(parent_id=parent_id, user_id=user_id,
                                                                 post_id=post_id,
                                                                 text=text)
                        new_comment.save()
                        comments = PostComment.objects.filter(post_id=post_id)
                        html_text = render_to_string("blog/includes/comment-component.html", {"comments": comments})
                        return JsonResponse({"html": html_text, "status": 200, "message": "نظر با موفقیت ثبت شد."})
                    else:
                        return JsonResponse({"status": 404, "message": "نظر پیدا نشد!"})


            else:
                return JsonResponse({"status": 400, "message": "متن نظر را وارد کنید!"})
        else:
            return JsonResponse({"status": 404, "message": "پست یافت نشد!"})
    return JsonResponse({"status": 302, "message": "شما وارد حساب خود نشده اید!"})

blog/templates/blog/includes/comment-component.html
<div class="response-area">
    <ul class="media-list">
        {% for comment in comments %}
            {% if not comment.parent_id %}
                <li class="media">

                    <a class="pull-right" href="#">
                        {% if request.user.avatar %}
                            <img class="media-object" src="{{ request.user.avatar.url }}" alt="">
                        {% else %}
                            <img class="media-object" style="border-radius: 10px;" src="/static/images/egiocMMHeJxW8ZDVer7lMv-xw7ReN-vH.jpeg" alt="">
                        {% endif %}
                    </a>
                    <div class="media-body">
                        <ul class="sinlge-post-meta">
                            <li><i class="fa fa-user"></i>{{ comment.user }}</li>
                            <li><i class="fa fa-calendar"></i>{{ comment.created|date }}</li>
                        </ul>
                        <p>{{ comment.text|linebreaks }}</p>
                        <button type="button" class="btn btn-primary" onclick="fillParentId({{ comment.id }})"><i
                                class="fa fa-reply"></i>پاسـخ
                        </button>
                    </div>
                </li>
                {% for second_comment in comment.postcomment_set.all %}
                    <li class="media second-media">
                        <a class="pull-right" href="#">
                            {% if request.user.avatar %}
                            <img class="media-object" src="{{ request.user.avatar.url }}" alt="">
                        {% else %}
                            <img class="media-object" style="border-radius: 10px;" src="/static/images/egiocMMHeJxW8ZDVer7lMv-xw7ReN-vH.jpeg" alt="">
                        {% endif %}
                        </a>
                        <div class="media-body">
                            <ul class="sinlge-post-meta">
                                <li><i class="fa fa-user"></i>{{ second_comment.user }}</li>
                                <li><i class="fa fa-calendar"></i>{{ second_comment.created|date }}</li>
                            </ul>
                            <p>{{ second_comment.text|linebreaks }}</p>
                            <button class="btn btn-primary" onclick="fillParentId({{ comment.id }})"><i
                                    class="fa fa-reply"></i>پاسـخ
                            </button>
                        </div>
                    </li>
                {% endfor %}


            {% endif %}
        {% endfor %}
    </ul>
</div><!--/Response-area-->

blog/templates/blog/includes/side-panel.html
<div class="col-sm-3">
                    <div class="left-sidebar">
                        <h2>دسته بندی پست ها</h2>
                        <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                            {% for category in categories %}
                                {% if not category.parent %}
                                    <div class="panel panel-default">
                                        <div class="panel-heading">
                                            <h4 class="panel-title">
                                                <a data-toggle="collapse" data-parent="#accordian"
                                                   href="#{{ category.slug }}">
                                                    <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                                    {{ category.title }}
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="{{ category.slug }}" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <ul>
                                                    {% for sub_category in category.category_set.all %}
                                                        <li><a href="">{{ sub_category.title }}</a></li>
                                                    {% endfor %}

                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div><!--/category-productsr-->
                        <div class="shipping text-center"><!--shipping-->
                            <img src="/static/images/Xiaomi-Mi-11-Ultra-2.jpg" height="329" width="270" alt=""/>
                        </div><!--/shipping-->

                    </div>
                </div>