blog/urls.py
from django.urls import path

from blog.views import PostListView, PostDetailView,add_comment

urlpatterns = [
    path("", PostListView.as_view(), name="post_list"),
    path("categories/<slug:category>/", PostListView.as_view(), name="post_category"),
    path("authors/<slug:username>/", PostListView.as_view(), name="post_author"),
    path("posts/<slug:slug>/", PostDetailView.as_view(), name="post_detail"),
    path('post-add-comment/', add_comment, name="post_add_comment"),
]

djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include("main.urls")),
    path('shop/', include("products.urls")),
    path('users/', include("users.urls")),
    path('cart/', include("cart.urls")),
    path('favorites/', include("favorites.urls")),
    path('blog/', include("blog.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import ProductListView, ProductDetailView, add_comment

urlpatterns = [
    path('', ProductListView.as_view(), name="shop"),
    path('categories/<slug:category>/', ProductListView.as_view(), name="categories"),
    path('brands/<slug:brand>/', ProductListView.as_view(), name="brands"),
    path('search/', ProductListView.as_view(), name="search"),
    path('products/<slug:slug>/', ProductDetailView.as_view(), name="product_detail"),
    path('product-add-comment/', add_comment, name="product_add_comment"),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT + "media/")

products/models.py
import os

from django.db import models
from django.utils.text import slugify
from django_jalali.db import models as jmodels

from users.models import User


def get_file_ext(file):
    return os.path.splitext(file)[1]


def product_name_generator(instance, file):
    ext = get_file_ext(file)
    return f"products/{instance.product.slug}/{instance.product.slug}{ext}"


class Category(models.Model):
    title = models.CharField(max_length=64, verbose_name="عنوان")
    english_title = models.CharField(max_length=64, verbose_name="عنوان انگلیسی")
    slug = models.SlugField(db_index=True, editable=False)
    parent = models.ForeignKey("Category", on_delete=models.CASCADE, verbose_name="دسته بندی والد", null=True,
                               blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.english_title)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"


class Brand(models.Model):
    title = models.CharField(max_length=64, verbose_name="عنوان")
    english_title = models.CharField(max_length=64, verbose_name="عنوان انگلیسی")
    slug = models.SlugField(db_index=True, editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.english_title)
        super(Brand, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "برند"
        verbose_name_plural = "برند ها"


class Product(models.Model):
    title = models.CharField(max_length=150, verbose_name="عنوان", blank=True, null=True)
    english_title = models.CharField(max_length=150, verbose_name="عنوان انگلیسی")
    slug = models.SlugField(max_length=150, editable=False)
    default_picture = models.ImageField(upload_to=product_name_generator, null=True,
                                        blank=True, verbose_name="عکس پیش فرض")
    created = jmodels.jDateTimeField(auto_now_add=True)
    modified = jmodels.jDateTimeField(auto_now=True)
    category = models.ManyToManyField(to=Category, verbose_name="دسته بندی")
    brand = models.ForeignKey(to=Brand, on_delete=models.CASCADE, verbose_name="برند")
    count = models.IntegerField(verbose_name="تعداد")
    price = models.IntegerField(verbose_name="قیمت")
    about = models.TextField(verbose_name="درباره محصول", blank=True, null=True)
    is_active = models.BooleanField(default=True, verbose_name="فعال/غیرفعال")

    def save(self, *args, **kwargs):
        if not self.title:
            self.title = self.english_title
        self.slug = slugify(self.english_title)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "محصول"
        verbose_name_plural = "محصولات"


class ProductPicture(models.Model):
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to=product_name_generator)
    is_default = models.BooleanField(default=False)

    class Meta:
        verbose_name = "تصویر محصول"
        verbose_name_plural = "تصاویر محصولات"
        ordering = ("-is_default",)


class ProductComment(models.Model):
    parent = models.ForeignKey("ProductComment", on_delete=models.CASCADE, blank=True, null=True, verbose_name="والد")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="کاربر")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="محصول")
    created = models.DateTimeField(auto_now_add=True)
    text = models.TextField(verbose_name="متن نظر")

    class Meta:
        ordering = "-created",


class ProductView(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    ip = models.CharField(max_length=32)

products/views.py
from django.db.models import Q
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.views.generic import ListView, DetailView

from .utils import slider_set_generator, get_client_ip
from .models import Product, ProductPicture, Category, Brand, ProductComment, ProductView


class ProductListView(ListView):
    template_name = "products/product-list.html"
    context_object_name = "products"
    paginate_by = 6

    def get_queryset(self):
        if category := self.kwargs.get("category"):
            queryset = Product.objects.filter(is_active=True, category__slug__exact=category).prefetch_related(
                "productpicture_set")
        elif brand := self.kwargs.get("brand"):
            queryset = Product.objects.filter(is_active=True, brand__slug__exact=brand).prefetch_related(
                "productpicture_set")
        elif search_query := self.request.GET.get("search"):
            queryset = Product.objects.filter(
                Q(title__icontains=search_query) | Q(english_title__icontains=search_query))
        else:
            queryset = Product.objects.filter(is_active=True).prefetch_related("productpicture_set")
        return queryset

    def get_context_data(self, **kwargs):
        _context = super(ProductListView, self).get_context_data()
        page_number = self.request.GET.get("page", 1)
        categories = Category.objects.all()
        brands = Brand.objects.all()
        context = {
            "page_number": int(page_number),
            "categories": categories,
            "brands": brands,
        }
        _context.update(context)
        return _context


class ProductDetailView(DetailView):
    template_name = "products/product-detail.html"
    # model = Product
    context_object_name = "product"

    def get_queryset(self):
        return Product.objects.filter(is_active=True).prefetch_related("productpicture_set")

    def get_context_data(self, **kwargs):
        _context = super(ProductDetailView, self).get_context_data()
        pictures = ProductPicture.objects.filter(product__slug=self.kwargs.get("slug"))
        pictures_set = slider_set_generator(pictures, 3)
        categories = Category.objects.all()
        brands = Brand.objects.all()
        related_products = Product.objects.filter(brand=self.object.brand).exclude(id=self.object.id).order_by(
            "-modified")[0:4]
        comments = ProductComment.objects.filter(product_id=self.object.id)
        ip = get_client_ip(self.request)
        visit = ProductView.objects.filter(product_id=self.object.id, ip=ip)
        if not visit.exists():
            new_visit = ProductView.objects.create(product_id=self.object.id, ip=ip)
            new_visit.save()
        context = {
            "pictures_set": pictures_set,
            "categories": categories,
            "brands": brands,
            "related_products": related_products,
            "comments": comments,
        }
        _context.update(context)
        return _context


def add_comment(request):
    if request.user.is_authenticated:
        parent_id = request.GET.get("parent_id")
        user_id = request.user.id
        product_id = request.GET.get("product_id")
        text = request.GET.get("text")
        product = Product.objects.filter(id=product_id)
        if product.exists():
            product = product.first()
            if text:
                if parent_id == "none":
                    new_comment = ProductComment.objects.create(parent_id=None, user_id=user_id, product_id=product_id,
                                                                text=text)
                    new_comment.save()
                    comments = ProductComment.objects.filter(product_id=product_id)
                    html_text = render_to_string("products/includes/comment-component.html", {"comments": comments})
                    return JsonResponse({"html": html_text, "status": 200, "message": "نظر با موفقیت ثبت شد."})
                else:
                    parent_comment = ProductComment.objects.filter(id=parent_id)
                    if parent_comment.exists():
                        new_comment = ProductComment.objects.create(parent_id=parent_id, user_id=user_id,
                                                                    product_id=product_id,
                                                                    text=text)
                        new_comment.save()
                        comments = ProductComment.objects.filter(product_id=product_id)
                        html_text = render_to_string("products/includes/comment-component.html", {"comments": comments})
                        return JsonResponse({"html": html_text, "status": 200, "message": "نظر با موفقیت ثبت شد."})
                    else:
                        return JsonResponse({"status": 404, "message": "نظر پیدا نشد!"})


            else:
                return JsonResponse({"status": 400, "message": "متن نظر را وارد کنید!"})
        else:
            return JsonResponse({"status": 404, "message": "محصول یافت نشد!"})
    return JsonResponse({"status": 302, "message": "شما وارد حساب خود نشده اید!"})

products/templates/products/includes/comment-component.html
<div class="response-area">
    <ul class="media-list">
        {% for comment in comments %}
            {% if not comment.parent_id %}
                <li class="media">

                    <a class="pull-right" href="#">
                        <img class="media-object" src="/static/images/blog/Customer.jpg" alt="">
                    </a>
                    <div class="media-body">
                        <ul class="sinlge-post-meta">
                            <li><i class="fa fa-user"></i>{{ comment.user }}</li>
                            <li><i class="fa fa-calendar"></i>{{ comment.created|date }}</li>
                        </ul>
                        <p>{{ comment.text|linebreaks }}</p>
                        <button type="button" class="btn btn-primary" onclick="fillParentId({{ comment.id }})"><i class="fa fa-reply"></i>پاسـخ</button>
                    </div>
                </li>
                {% for second_comment in comment.productcomment_set.all %}
                    <li class="media second-media">
                        <a class="pull-right" href="#">
                            <img class="media-object" src="/static/images/blog/Customer.jpg" alt="">
                        </a>
                        <div class="media-body">
                            <ul class="sinlge-post-meta">
                                <li><i class="fa fa-user"></i>{{ second_comment.user }}</li>
                                <li><i class="fa fa-calendar"></i>{{ second_comment.created|date }}</li>
                            </ul>
                            <p>{{ second_comment.text|linebreaks }}</p>
                            <button class="btn btn-primary" onclick="fillParentId({{ comment.id }})"><i
                                    class="fa fa-reply"></i>پاسـخ</button>
                        </div>
                    </li>
                {% endfor %}


            {% endif %}
        {% endfor %}
    </ul>
</div><!--/Response-area-->

products/templates/products/includes/sidepanel.html
<div class="left-sidebar">
    <h2>دسته بندی محصولات</h2>
    <div class="panel-group category-products" id="accordian"><!--category-productsr-->
        {% for category in categories %}
            {% if not category.parent_id %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordian" href="#{{ category.slug }}">
                                <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                {{ category }}
                            </a>
                        </h4>
                    </div>
                    <div id="{{ category.slug }}" class="panel-collapse collapse">
                        <div class="panel-body">
                            <ul>
                                <li><a href="{% url "categories" category=category.slug %}">{{ category }}</a></li>
                                {% for category_ in category.category_set.all %}
                                    <li><a href="{% url "categories" category=category_.slug %}">{{ category_ }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <div class="brands_products"><!--brands_products-->
        <h2>برنـد ها</h2>
        <div class="brands-name">
            <ul class="nav nav-pills nav-stacked">
                {% for brand in brands %}
                    <li><a href="{% url "brands" brand=brand.slug %}"> <span
                            class="pull-left">({{ brand.product_set.count }})</span>{{ brand.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div><!--/brands_products-->

    <div class="price-range"><!--price-range-->
        <h2>فیلتـر قیمـت</h2>
        <div class="well">
            <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="100000000"
                   data-slider-step="10000" data-slider-value="[1000,50000000]" id="sl2"><br/>
            <b>1.000.000 ريال</b> <b class="pull-left">0 ريال</b>
        </div>
    </div><!--/price-range-->

    <div class="shipping text-center"><!--shipping-->
        <img src="/static/images/Xiaomi-Mi-11-Ultra-2.jpg" height="335" width="270" alt=""/>
    </div><!--/shipping-->

</div>