blog/urls.py
from django.urls import path

from blog.views import PostListView, PostDetailView,add_comment

urlpatterns = [
    path("", PostListView.as_view(), name="post_list"),
    path("categories/<slug:category>/", PostListView.as_view(), name="post_category"),
    path("authors/<slug:username>/", PostListView.as_view(), name="post_author"),
    path("posts/<slug:slug>/", PostDetailView.as_view(), name="post_detail"),
    path('post-add-comment/', add_comment, name="post_add_comment"),
]

djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include("main.urls")),
    path('shop/', include("products.urls")),
    path('users/', include("users.urls")),
    path('cart/', include("cart.urls")),
    path('favorites/', include("favorites.urls")),
    path('blog/', include("blog.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from .views import HomeView, AboutUsView, ContactUsView, newsletter

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("about-us/", AboutUsView.as_view(), name="about"),
    path("contact-us/", ContactUsView.as_view(), name="contact"),
    path("newsletter/", newsletter, name="newsletter"),
]

main/models.py
import os

from django.db import models


def get_file_ext(file):
    return os.path.splitext(file)[1]


def slider_name_generator(instance, file):
    ext = get_file_ext(file)
    return f"banners/{instance.title}/{instance.title}{ext}"


class Phone(models.Model):
    phone = models.CharField(max_length=14, verbose_name="شماره تماس")

    def __str__(self):
        return self.phone

    class Meta:
        verbose_name = "شماره تماس"
        verbose_name_plural = "شماره تماس ها"


class SiteSetting(models.Model):
    title = models.CharField(max_length=72, verbose_name="عنوان")
    logo = models.ImageField(upload_to="media/site_logos/", verbose_name="لوگوی سایت")
    about_text = models.TextField()
    address = models.TextField()
    phone = models.ManyToManyField(to=Phone, verbose_name="شماره تماس(ها)")
    fax = models.CharField(max_length=72, verbose_name="فکس")
    email = models.EmailField(max_length=72, verbose_name="ایمیل")
    instagram = models.CharField(max_length=72, verbose_name="اینستاگرام")
    telegram = models.CharField(max_length=72, verbose_name="تلگرام")
    twitter = models.CharField(max_length=72, verbose_name="توییتر")
    additional_about_text = models.TextField(verbose_name="توضیحات اضافی")
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "تنظیمات"
        verbose_name_plural = "تنظیمات سایت"


class Slider(models.Model):
    title = models.CharField(max_length=128, verbose_name="عنوان")
    banner = models.ImageField(upload_to=slider_name_generator, verbose_name="بنر")
    text = models.TextField(verbose_name="متن")
    url = models.URLField(verbose_name="لینک")
    is_active = models.BooleanField(default=False, verbose_name="فعال/غیرفعال")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "بنر"
        verbose_name_plural = "بنر های سایت"


class Newsletter(models.Model):
    email = models.EmailField(unique=True)

products/models.py
import os

from django.db import models
from django.utils.text import slugify
from django_jalali.db import models as jmodels

from users.models import User


def get_file_ext(file):
    return os.path.splitext(file)[1]


def product_name_generator(instance, file):
    ext = get_file_ext(file)
    return f"products/{instance.product.slug}/{instance.product.slug}{ext}"


class Category(models.Model):
    title = models.CharField(max_length=64, verbose_name="عنوان")
    english_title = models.CharField(max_length=64, verbose_name="عنوان انگلیسی")
    slug = models.SlugField(db_index=True, editable=False)
    parent = models.ForeignKey("Category", on_delete=models.CASCADE, verbose_name="دسته بندی والد", null=True,
                               blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.english_title)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"


class Brand(models.Model):
    title = models.CharField(max_length=64, verbose_name="عنوان")
    english_title = models.CharField(max_length=64, verbose_name="عنوان انگلیسی")
    slug = models.SlugField(db_index=True, editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.english_title)
        super(Brand, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "برند"
        verbose_name_plural = "برند ها"


class Product(models.Model):
    title = models.CharField(max_length=150, verbose_name="عنوان", blank=True, null=True)
    english_title = models.CharField(max_length=150, verbose_name="عنوان انگلیسی")
    slug = models.SlugField(max_length=150, editable=False)
    default_picture = models.ImageField(upload_to=product_name_generator, null=True,
                                        blank=True, verbose_name="عکس پیش فرض")
    created = jmodels.jDateTimeField(auto_now_add=True)
    modified = jmodels.jDateTimeField(auto_now=True)
    category = models.ManyToManyField(to=Category, verbose_name="دسته بندی")
    brand = models.ForeignKey(to=Brand, on_delete=models.CASCADE, verbose_name="برند")
    count = models.IntegerField(verbose_name="تعداد")
    price = models.IntegerField(verbose_name="قیمت")
    about = models.TextField(verbose_name="درباره محصول", blank=True, null=True)
    is_active = models.BooleanField(default=True, verbose_name="فعال/غیرفعال")

    def save(self, *args, **kwargs):
        if not self.title:
            self.title = self.english_title
        self.slug = slugify(self.english_title)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "محصول"
        verbose_name_plural = "محصولات"


class ProductPicture(models.Model):
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to=product_name_generator)
    is_default = models.BooleanField(default=False)

    class Meta:
        verbose_name = "تصویر محصول"
        verbose_name_plural = "تصاویر محصولات"
        ordering = ("-is_default",)


class ProductComment(models.Model):
    parent = models.ForeignKey("ProductComment", on_delete=models.CASCADE, blank=True, null=True, verbose_name="والد")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="کاربر")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="محصول")
    created = models.DateTimeField(auto_now_add=True)
    text = models.TextField(verbose_name="متن نظر")

    class Meta:
        ordering = "-created",


class ProductView(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    ip = models.CharField(max_length=32)

main/forms.py
from django import forms


class ContactUsForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "ایمیل", "class": "form-control"}),
                             label="ایمیل")
    name_and_family = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "نام و نام خانوادگی", "class": "form-control"}),
        max_length=72, label="نام و نام خانوادگی")
    subject = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "موضوع", "class": "form-control"}),
                              max_length=72, label="موضوع")
    message = forms.CharField(
        widget=forms.Textarea(attrs={"placeholder": "متن پیام", "class": "form", "rows": "10"}),
        label="متن پیام")

main/views.py
from django.db.models import Count
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.views.generic.base import TemplateView

from main.forms import ContactUsForm
from products.utils import slider_set_generator
from blog.models import Category as BlogCategory
from main.models import SiteSetting, Slider, Newsletter
from products.models import Category as ShopCategory, Product


class HomeView(TemplateView):
    template_name = "main/home.html"

    def get_context_data(self, **kwargs):
        _context = super(HomeView, self).get_context_data(**kwargs)
        sliders = Slider.objects.filter(is_active=True)
        most_viewed = Product.objects.filter(is_active=True).annotate(views=Count("productview")).order_by("-views")[:8]
        most_viewed = slider_set_generator(most_viewed, 4)
        recent_products = Product.objects.filter(is_active=True).order_by("-created")[:8]
        recent_products = slider_set_generator(recent_products, 4)
        print(most_viewed)
        context = {
            "sliders": sliders,
            "most_viewed": most_viewed,
            "recent_products": recent_products,
        }
        _context.update(context)
        return _context


class AboutUsView(TemplateView):
    template_name = "main/about.html"

    def get_context_data(self, **kwargs):
        setting = SiteSetting.objects.filter(is_active=True).first()
        _context = super(AboutUsView, self).get_context_data(**kwargs)
        context = {
            "setting": setting
        }
        _context.update(context)
        return _context


class ContactUsView(FormView):
    template_name = "main/contact.html"
    form_class = ContactUsForm
    success_url = reverse_lazy("contact")

    def form_valid(self, form):
        email = form.cleaned_data.get("email")
        name_and_family = form.cleaned_data.get("name_and_family")
        subject = form.cleaned_data.get("subject")
        message = form.cleaned_data.get("message")
        # todo : send mail
        return super(ContactUsView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        setting = SiteSetting.objects.filter(is_active=True).first()
        _context = super(ContactUsView, self).get_context_data(**kwargs)
        context = {
            "setting": setting
        }
        _context.update(context)
        return _context


def newsletter(request):
    if request.method == "POST":
        email = request.POST.get("email")
        if email:
            try:
                new_email = Newsletter.objects.create(email=email)
                new_email.save()
                return render(request, "main/newsletter.html", {
                    "status": 1
                })
            except:
                return render(request, "main/newsletter.html", {
                    "status": 0
                })
        return render(request, "main/newsletter.html", {
            "status": 0
        })


def header_component(request):
    shop_categories = ShopCategory.objects.filter(parent_id=None)
    blog_categories = BlogCategory.objects.filter(parent_id=None)

    return render(request, "includes/header-component.html", {
        "shop_categories": shop_categories,
        "blog_categories": blog_categories,
    })


def footer_component(request):
    setting = SiteSetting.objects.get(is_active=True)
    return render(request, "includes/footer-component.html", {"setting": setting})

main/templates/main/about.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    درباره ما
{% endblock %}
{% block body_content %}
    <div id="contact-page" class="container">
        <div class="bg">

            <div class="row">
                <div class="col-sm-4">
                    <div class="contact-info">
                        <img src="{{ setting.logo.url }}" width="300" height="200" class="img-responsive"/>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="about">
                        <h2 class="title text-center">دربـاره ما</h2>
                        <p class="about-desc">
                            {{ setting.about_text|linebreaks }}
                        </p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12 about-address">
                    <address>
                        <p>{{ setting.title }} | {{ setting.address }}
                            - پلاک 54 | تلفن تماس : {{ setting.phone.all.first }} | فکس : {{ setting.fax }} | ایمیـل
                            : {{ setting.email }}
                        </p>
                    </address>
                </div>
            </div>

            <div class="row">
                <div class="container">
                    <div class="col-sm-12" style="overflow: hidden; margin-bottom: 40px"><h2 class="title text-center">
                        مـا اینجـا هستیـم ... </h2>
                        <div id="gmap" class="contact-map">
                            <img src="{% static "images/home/Map.jpg" %}" alt="Map"/>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div><!--/#contact-page-->
{% endblock %}


main/templates/main/contact.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    تماس با ما
{% endblock %}
{% block body_content %}
    <div id="contact-page" class="container">
        <div class="bg">
            <div class="row">
                <div class="container">
                    <div class="col-sm-12" style="overflow: hidden; margin-bottom: 40px">
                        <h2 class="title text-center">تمـاس با مـا</h2>
                        <div id="gmap" class="contact-map">
                            <img src="{% static "images/home/Map.jpg" %}" alt="Map"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-8">
                    <div class="contact-form">
                        <h2 class="title text-center">با ما در ارتباط باشیـد</h2>
                        <div class="status alert alert-success" style="display: none"></div>
                        <form id="main-contact-form" class="contact-form row" name="contact-form" method="post">
                            {% csrf_token %}
                            <div class="form-group col-md-6">
                                {{ form.name_and_family.label_tag }}
                                {{ form.name_and_family }}
                            </div>
                            <div class="form-group col-md-6">
                                {{ form.email.label_tag }}
                                {{ form.email }}
                            </div>
                            <div class="form-group col-md-12">
                                {{ form.subject.label_tag }}
                                {{ form.subject }}
                            </div>
                            <div class="form-group col-md-12">
                                {{ form.message.label_tag }}
                                {{ form.message }}
                            </div>
                            <div class="form-group col-md-12">
                                <input type="submit" name="submit" class="btn btn-primary pull-right" value="ارسـال">
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="contact-info">
                        <h2 class="title text-center">اطلاعات تماس</h2>
                        <address>
                            <p>{{ setting.title }}</p>
                            <p>{{ setting.address }}</p>
                            <p>تلفن تماس : </p>
                            {% for phone in setting.phone.all %}
                                <p>{{ phone }}</p>
                            {% endfor %}

                            <p>فکس : {{ setting.fax }}</p>
                            <p style="font-family: tahoma;">ایمیـل : {{ setting.email }}</p>
                        </address>
                        <div class="social-networks">
                            <h2 class="title text-center">شبکـه های اجتـماعی</h2>
                            <span class="socials-share share">
									<ul>
										<a href="{{ setting.instagram }}">
											<li>
												<label>اینستاگرام</label>
												<img src="{% static "images/socials/5fcb1110d6c18c0c11093c6a_Instagram-01-p-1600.png" %}"
                                                     width="40" height="40"/>
											</li>
										</a>
										<a href="{{ setting.telegram }}">
											<li>
												<label>تلگرام</label>
												<img src="{% static "images/socials/3W72119s5BjWPGGUiZ9pqnZoj8JHYxCCp9dtn2QVeutFMyS7USjQzFhQBankXumkpSBD1yM1k24zdp3M4hxygjV1CEEMZAfGnBdLVoHgQ94F6JaFe3UCw8.png" %}"
                                                     width="32" height="32"/>
											</li>
										</a>
										<a href="{{ setting.twitter }}">
											<li>
												<label>توییتر</label>
												<img src="{% static "images/socials/social-media-computer-icons-logo-facebook-social-network-chimichanga.jpg" %}"
                                                     width="32" height="32"/>
											</li>
										</a>
									</ul>
								</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/#contact-page-->
{% endblock %}


main/templates/main/home.html
{% extends "base.html" %}
{% load poll_extras %}
{% block title %}
    صفحه اصلی
{% endblock %}

{% block body_content %}
    <section id="slider"><!--slider-->
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div id="slider-carousel" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            {% for slider in sliders %}
                                <li data-target="#slider-carousel" data-slide-to="{{ forloop.counter0 }}"
                                    {% if forloop.first %}class="active"{% endif %}></li>
                            {% endfor %}

                        </ol>

                        <div class="carousel-inner">

                            {% for slider in sliders %}
                                <div class="item {% if forloop.first %}active{% endif %}">
                                    <a href="{{ slider.url }}">
                                        <div class="col-sm-6">
                                            <h1>{{ slider.title }}</h1>
                                            <p>{{ slider.text|linebreaks }}</p>
                                        </div>
                                        <div class="col-sm-6">
                                            <img src="{{ slider.banner.url }}" class="girl img-responsive" width="450"
                                                 height="441" alt=""/>
                                        </div>
                                    </a>
                                </div>
                            {% endfor %}


                        </div>

                        <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="prev">
                            <i class="fa fa-angle-right"></i>
                        </a>
                        <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="next">
                            <i class="fa fa-angle-left"></i>
                        </a>
                    </div>

                </div>
            </div>
        </div>
    </section><!--/slider-->

    <section>
        <div class="container">
            <div class="row">

                <div class="recommended_items"><!--NewProduct_items-->
                    <h2 class="title text-center">پر بازدید ترین محصولات</h2>

                    <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                            {% for list in most_viewed %}
                                <div class="item {% if forloop.first %}active{% endif %} ">
                                    {% for item in list %}
                                        <div class="col-sm-3">
                                            <div class="product-image-wrapper">
                                                <div class="single-products">
                                                    <div class="productinfo text-center">
                                                        <img src="{{ item.productpicture_set.all.first.picture.url }}"
                                                             alt=""/>
                                                        <h2>{{ item.price|currency }} ریال</h2>
                                                        <p>{{ item.title }}</p>
                                                        <a href="#" class="btn btn-default add-to-cart"><i
                                                                class="fa fa-shopping-cart"></i>افزودن به سبـد خرید</a>
                                                    </div>

                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}

                                </div>
                            {% endfor %}
                        </div>
                        <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
                            <i class="fa fa-angle-left"></i>
                        </a>
                        <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
                            <i class="fa fa-angle-right"></i>
                        </a>
                    </div>
                </div><!--/NewProduct_items-->

                <div class="col-sm-12 padding-right">
                    <div class="features_items"><!--RetailSale_items-->
                        <a href="shop-2.html"><h2 class="title text-center">جدیدترین محصولات</h2></a>
                        <div id="new-item-carousel" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                {% for list in recent_products %}
                                    <div class="item {% if forloop.first %}active{% endif %}">
                                        {% for item in list %}
                                            <div class="col-sm-3">
                                                <div class="product-image-wrapper">
                                                    <div class="single-products">
                                                        <div class="productinfo text-center">
                                                            <img src="{{ item.productpicture_set.all.first.picture.url }}"
                                                                 alt=""/>
                                                            <h2>{{ item.price|currency }} ریال</h2>
                                                            <p>{{ item.title }}</p>
                                                            <a href="#" class="btn btn-default add-to-cart"><i
                                                                    class="fa fa-shopping-cart"></i>افزودن به سبـد خریـد</a>
                                                        </div>
                                                        <div class="product-overlay">
                                                            <div class="overlay-content">
                                                                <h2>2.500.000 R</h2>
                                                                <p>توضیحات کوتاه محصـول</p>
                                                                <a href="#" class="btn btn-default add-to-cart"><i
                                                                        class="fa fa-shopping-cart"></i>افزودن به سبـد
                                                                    خریـد</a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="choose">
                                                        <ul class="nav nav-pills nav-justified">
                                                            <li>
                                                                <a href="#">
                                                                    <i class="fa fa-plus-square"></i>لیست علاقه مندی ها
                                                                </a>
                                                            </li>
                                                            <li><a href="#"><i class="fa fa-plus-square"></i>مقایسه</a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                {% endfor %}

                            </div>
                            <a class="left recommended-item-control" href="#new-item-carousel" data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a class="right recommended-item-control" href="#new-item-carousel" data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </div><!--RetailSale_items-->


                </div>

            </div>
        </div>
    </section>
{% endblock %}

main/templates/main/newsletter.html
{% extends "base.html" %}

{% block title %}
    خبرنامه
{% endblock %}

{% block body_content %}
    {% if status %}
        <div class="text-center">
            <h3 class="text-success">
                شما در خبر نامه عضو شدید.
            </h3>
            <button type="button" class="btn btn-primary" onclick="window.location.href='{% url "home" %}'">برو به صفحه
                اصلی
            </button>
        </div>
    {% else %}
        <div class="text-center">
            <h3 class="text-danger">
                عضویت با خطا مواجه شد!
            </h3>
            <h5> لطفا دوباره امتحان کنید.
            </h5>
            <button type="button" class="btn btn-primary" onclick="window.location.href='{% url "home" %}'">برو به صفحه
                اصلی
            </button>
        </div>
    {% endif %}
    <br>
{% endblock %}